
# Test Login
POST http://127.0.0.1:8000/dj-rest-auth/login/
Content-Type: application/json

{
   
    "email":"new@gmail.com",
    "password":"modijay72"
}

# # Test Registratoin
# POST http://127.0.0.1:8000/dj-rest-auth/registration/
# Content-Type: application/json

# {
#     "username":"new",
#     "email":"new@gmail.com",
#     "password1":"xxxxx",
#     "password2":"xxx"
# }
