# Generated by Django 3.1.2 on 2020-12-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0003_auto_20201212_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='educatorr',
            name='gender',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='educatorr',
            name='staff_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentt',
            name='admission_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentt',
            name='gender',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
