# Generated by Django 3.1.2 on 2020-12-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0004_auto_20201212_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Educatorr',
            new_name='Educator',
        ),
        migrations.RenameModel(
            old_name='Studentt',
            new_name='Student',
        ),
    ]
