# Generated by Django 3.1.2 on 2020-12-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0006_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='coursework.Course'),
        ),
    ]
