# Generated by Django 3.1.2 on 2020-12-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20201215_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='slug',
            field=models.SlugField(default='aahdfia8', max_length=100),
        ),
    ]
