# Generated by Django 3.1.2 on 2020-12-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0002_auto_20201212_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Educatorr',
        ),
        migrations.RenameModel(
            old_name='Educator',
            new_name='Studentt',
        ),
    ]
