# Generated by Django 3.1.2 on 2020-12-22 17:33

import coursework.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0005_auto_20201212_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='Course created successfully.Description should be inserted anytime soon')),
                ('slug', models.SlugField()),
                ('thumbnail', models.ImageField(upload_to=coursework.models.upload_post_image)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('educator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursework.educator')),
            ],
        ),
    ]
