# Generated by Django 3.1.2 on 2020-12-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0008_module_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='page_number',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
