# Generated by Django 3.1.2 on 2020-12-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20201210_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graded_assignment',
            options={'ordering': ['-id']},
        ),
    ]
