# Generated by Django 3.1.2 on 2020-12-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_assignment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='educator',
        ),
        migrations.RemoveField(
            model_name='graded_assignment',
            name='student',
        ),
        migrations.DeleteModel(
            name='Educator',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
